### ISSUE TITLE
Automatically add repos that have atleast one release

### ISSUE THREAD

**Issue by captn3m0** [vfeskov/WinABeer#18]
I have 1k+ starred repos and going through

![image](https://user-images.githubusercontent.com/584253/36727086-f9edf5ae-1be1-11e8-9054-40752d5bd63d.png)

page by page is impossible for me. If it automatically watched any projects that have atleast 1 release, that would be awesome.

Also, huge :+1: for releasing this and making it open source. I have devmail.in registered for the exact same project (I'd planned for weekly/daily emails). Would be happy to transfer if you wanna stake it.

I had some monetization ideas at https://github.com/captn3m0/ideas#newsletters-for-github if you'd be interested.

**Comment by vfeskov** [comment]
thanks for the offer, i'll consider it if i chose to rename the project

the request duplicates https://github.com/vfeskov/WinABeer/issues/16 , i will update that one once i complete it
