### ISSUE TITLE
Feedback on the name

### ISSUE THREAD

**Issue by neokio** [vfeskov/WinABeer#19]
I have a REALLY hard time taking anything named "WinABeer" seriously.
Other than the title, everything about this is pretty excellent!

Great work, recommend renaming it.

**Comment by MaikuMori** [comment]
Why so serious?

**Comment by vfeskov** [comment]
im thinking about it, so far i haven't monetized the project in any way and the name being funny doesn't matter all that much.

on the other hand, it was an acronym from 
> it **WI**ll **N**otify **AB**out **RE**l**E**ases
would mentioning this somewhere make it more serious, what do you think?

**Comment by vfeskov** [comment]
well the name does matter anyway, even if i don't monetize it

**Comment by TPS** [comment]
Why not run it under 2 domains, e.g., a "serious" version to monetize (e.g., private repos, &c), & the current version left mostly as-is?

**Comment by TPS** [comment]
@vfeskov So, FYI, WinABeer _isn't_ redirecting to GitPunch, but seems to be a kinda-inactive _clone_, right now. (Running the pages side-by-side, G👊 allows more repos that Wa🍺, for unknown reasons.)  →  Intentional?

**Comment by TPS** [comment]
@vfeskov Also, you forgot to update that AWS Dashboard screenshot to G👊.

**Comment by vfeskov** [comment]
@TPS yeah service worker cache prevents it from redirecting to the new url, I didn't come up with a solution for this, try deleting cache

**Comment by TPS** [comment]
@vfeskov I don't quite understand.…  You can't setup a [direct HTTP 301 permanent redirect](https://en.m.wikipedia.org/wiki/HTTP_301) @ WinABeer.com?
