### ISSUE TITLE
The word "win" make QQ mailbox show a security warning

### ISSUE THREAD

**Issue by gdh1995** [vfeskov/WinABeer#21]
Thanks for your prefect work! It shows some tips like "Please notice DO NOT input your password or trust any prize info".

Is there any graceful solution to avoid such warnings?

**Comment by vfeskov** [comment]
aw shucks

**Comment by TPS** [comment]
Maybe whatever resolution of #19 will solve this?

**Comment by vfeskov** [comment]
Hmm well I tested qq.com myself, I sent emails with different text and links, and it was showing the alert when the email had winabeer.com link in it. New emails don't have this link anymore, please tell me if you ever see this alert again
