### ISSUE TITLE
Adding 13th repository to watch failing :(

### ISSUE THREAD

**Issue by hartwork** [vfeskov/WinABeer#23]
Hi!

Missed the hack+tell yesterday, damn! Is there a relationship to sibbell.com's recent pledge (..) that you made this or is it just fortunate timing?

I have toggled 12 of my starred repositories for notification. It keeps failing on the 13th now — https://github.com/EdSchouten/hidesvn to be precise — without indication why. The slider just won't toggle. Is there a limit I'm hitting here? A bug? Any thoughts?

Best, Sebastian

**Comment by vfeskov** [comment]
@hartwork winabeer.com has been operational for 5 months now, and i made it not knowing that there was sibbell.com tbh.

anyway, the problem with EdSchouten/hidesvn is that it has no tags/releases on github, and i decided not to allow monitoring such repos to save costs. i will eventually add a proper error message when you try to toggle such a repo

**Comment by hartwork** [comment]
> @hartwork winabeer.com has been operational for 5 months now, and i made it not knowing that there was sibbell.com tbh.

It's cool to have you're because it's free software and I was about to start a project like that myself, because sibbell.com threatened to shut down the free version unless enough people starting paying 15(!) USD per year. See this:
![sibbell_pledge_mail](https://user-images.githubusercontent.com/1577132/39253882-316c2e44-48a9-11e8-80d3-f3eae5ca780e.png)

> anyway, the problem with EdSchouten/hidesvn is that it has no tags/releases on github, and i decided not to allow monitoring such repos to save costs. i will eventually add a proper error message when you try to toggle such a repo

I see, thanks!
